object PopupForm: TPopupForm
  Left = 0
  Top = 0
  BorderStyle = bsNone
  Caption = 'PopupForm'
  ClientHeight = 256
  ClientWidth = 256
  Color = clBtnFace
  DoubleBuffered = True
  Font.Charset = DEFAULT_CHARSET
  Font.Color = clWindowText
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  FormStyle = fsStayOnTop
  OldCreateOrder = False
  Position = poDesigned
  Scaled = False
  PixelsPerInch = 96
  TextHeight = 13
end
